version: '3.8'

services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    build:
      context: ./backend
    container_name: backend
    networks:
      - app-network
    depends_on:
      - db
      - bank-db  # Добавили зависимость от банковской БД
      - minio
      - redis
    env_file:
      - .env
    ports:
      - '8081:8081'
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  # Добавляем новую службу для банковской БД
  bank-db:
    image: postgres:15.1-alpine
    container_name: postgres-bank
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${BANK_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${BANK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BANK_POSTGRES_DATABASE}
    volumes:
      - ./src/main/resources/bank-db-init:/docker-entrypoint-initdb.d  # Опционально, если нужны инициализирующие скрипты
      - bank-db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'  # Меняем порт на 5433, чтобы не конфликтовать с основной БД

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app-network
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
  db-data:
    driver: local
  bank-db-data:  # Добавили том для банковской БД
    driver: local
  minio-data:
    driver: local

networks:
  app-network:
    driver: bridge